### ISSUE TITLE
Need to Increase Text Contrast on Subfolders

### ISSUE THREAD

**Issue by KzBeck** [Slowbad/obsidian-solarized#12] opened 2021-05-13 14:12 UTC
First of all I love the theme, thank you for your time to create it.

I am using the Colored Folders snippet in Obsidian and I would like to be able to increase the contrast on Solarize for my subfolders.  I was able to change the main folders to white, which provides enough contrast, but I also need to do the same for my subfolders.  I have tried.  I  have looked in both CSS files, but am unable to find the location to make this alteration. 

Your help would be appreciated.

**Comment by harmtemolder** [comment] 2021-05-20 13:12
Could you point me to this Colored Folders snippet? And maybe add a screenshot of what you’re seeing, so I can get an idea of what you’re trying to accomplish?

**Comment by harmtemolder** [comment] 2022-11-21 15:27
Closing this because I can't reproduce the issue

**Closed as not planned** 2022-11-21 15:27 UTC
